Feat profile
RiusmaX/MDS-MBA1-SocialNetwork pull request #1
Opened 2023-04-13 14:01 UTC by CedricLahaye

Ajoute la page "profile" des utilisateurs

2023-04-13 14:20 UTC, RiusmaX requested changes

2023-04-13 14:20 UTC, RiusmaX commented on frontend/src/components/Layout/Button.jsx
> +
Ajouter un commentaire

2023-04-13 14:20 UTC, RiusmaX commented on frontend/src/components/Layout/Button.jsx
> +    <div className={'button ' + (className !== '' && className)} onClick={() => { onClick !== null && onClick() }}>
`() => { onClick !== null && onClick() }`

`onClick && onClick`

2023-04-13 14:20 UTC, RiusmaX commented on frontend/src/components/Profile/Avatar.jsx
> +      setTimeout(() => {
A déplacer dans une promesse

2023-04-13 14:20 UTC, RiusmaX commented on frontend/src/components/Profile/Avatar.jsx
> +      onClick={handlePress}
handleClick

2023-04-13 14:20 UTC, RiusmaX commented on frontend/src/components/Profile/FullName.jsx
>  const FullName = ({ firstName, lastName, username }) => {
Ajouter un commentaire

2023-04-13 14:20 UTC, RiusmaX commented on frontend/src/index.js
> +import './styles/Reset.scss'
A deplacer dans un globals.scss avec un fichier mixins et un fichier de variables

2023-04-27 09:56 UTC, JPreault commented on frontend/src/components/Profile/Avatar.jsx
> +      setTimeout(() => {
Non, pas possible sans utiliser de trop grosses solutions

2023-04-27 10:17 UTC, RiusmaX approved these changes
GG

2023-04-27 10:18 UTC, RiusmaX approved these changes

2023-04-27 10:21 UTC, merged